### ISSUE TITLE
国服comd 1.9.47dump失败

### ISSUE THREAD

**Issue by yyyy1314** [Poko-Apps/Il2CppDumperCODM#1]
![Desktop Screenshot 2024 09 01 - 13 17 04 50](https://github.com/user-attachments/assets/412e2863-7e1f-4df6-8d26-38d6a272cec5)

**Comment by Poko-Apps** [comment]
Hey, the **libil2cpp.so** is protected (encrypted) that's why dump failed. You need to get the il2cpp binary from game's memory at runtime.

**Comment by Poko-Apps** [comment]
As there's no problem in dumper I'm closing this issue.
